language: python

python:
  - "2.7"
  - "3.3"

#install: "sudo apt-get -qq install libfreetype6-dev liblcms1-dev libwebp-dev"
install:
#  - "git clone https://github.com/ccinfra/conf.git"
  - pip install coveralls --use-mirrors

script:
#  - python setup.py clean
#  - python setup.py install
#  - python selftest.py
#  - python tests/run.py --installed
#  - python unittest_ccinfra.py --installed
  - coverage run unittest_ccinfra.py --installed
  - coverage report -m
  - coveralls --verbose

branches:
  only:
      - master

after_sucess:
  - coveralls --verbose
