language: python

python:
  - "2.7"
#  - "3.3"

#install: "sudo apt-get -qq install libfreetype6-dev liblcms1-dev libwebp-dev"
install:
#  - "git clone https://github.com/ccinfra/conf.git"
  - pip install coveralls --use-mirrors

script:
#  - python setup.py clean
#  - python setup.py install
#  - python selftest.py
#  - python tests/run.py --installed
#  - python unittest_ccinfra.py --installed
#  - coverage run unittest_ccinfra.py --installed
  - coverage run --source=ccinfra setup.py test
  - coverage report -m

branches:
  only:
    - master

notifications:
  email:
    - vonpupp@gmail.com

after_script:
  - coveralls --verbose
