language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

#install: "sudo apt-get -qq install libfreetype6-dev liblcms1-dev libwebp-dev"

#script:
#  - python setup.py clean
#  - python setup.py install
#  - python selftest.py
#  - python Tests/run.py --installed

branches:
  only:
      - master
